# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0002_auto_20160403_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
