# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0004_subscriber_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
