# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0005_auto_20160403_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
    ]
