# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0006_remove_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='op',
            field=models.CharField(default='Authors Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='dynamo.com'),
            preserve_default=False,
        ),
    ]
