# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0007_auto_20160404_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
