# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynotify', '0008_auto_20160405_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=400, unique=True),
        ),
    ]
